### ISSUE TITLE
Subpar not generating a correct PAR file

### ISSUE THREAD

**Issue by gnufreak** [google/subpar#10] opened 2016-10-05 11:41 UTC
When I build my "binary" with bazel build some_app.par, it builds a self-contained PAR file but doesn't set the correct sys.path through the boilerplate code prepended to my actual application.

When I try to run some_app.par, it complains that it's unable to import its dependencies:

```
%  ../../bazel-bin/code/some_app/some_app.par
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "../../bazel-bin/code/some_app/some_app.par/__main__.py", line 23, in <module>
ImportError: No module named code.util
```

**Some details**

In the workspace definition, I defined an external GIT repository that provides the extension required to build PAR files:

```
~/workspace $ cat WORKSPACE
git_repository(
name = "subpar",
remote = "https://github.com/google/subpar.git",
# Commit on 2016-08-06.
commit = "e77b91cc277fa8239596eff94b326af60185b62e",
)
```

The some_app's BUILD file is fairly simple:

```
~/workspace/some_app $ cat BUILD
package(default_visibility = ["//visibility:public"])
load("@subpar//:subpar.bzl", "par_binary")

par_binary(
  name = "some_app",
  srcs = ["some_app.py"],
  deps = [
    "//code/util:some_library",
    "//code/util:log",
  ],
)
```

The util BUILD file isn't rocket science either:

```
~/workspace/some_app $ cat ../util/BUILD
package(default_visibility = ["//visibility:public"])

py_library(
  name = "some_library",
  srcs = ["some_library.py"],
)

py_library(
  name = "some_log",
  srcs = ["log.py"],
)
```

Imports from some_app.py:

```
$ grep import some_app.py
import os
import time
from code.util import some_library
from code.util import log
```

When I unzipped the PAR file, it looks like all dependencies are there but sys.path isn't getting modified by the boilerplate code for them to be found:

```
% find /tmp/unzipped_parfile

__main__
__main__/code
__main__/code/some_app
__main__/code/some_app/some_app.py
__main__/code/some_app/__init__.py
__main__/code/some_app/some_app
__main__/code/util
__main__/code/util/__init__.py
__main__/code/util/some_library.py
__main__/code/util/log.py
__main__/code/__init__.py
subpar
subpar/__init__.py
subpar/runtime
subpar/runtime/__init__.py
subpar/runtime/support.py
__main__.py
```

**Comment by duggelz** [comment] 2016-10-05 18:59
Thanks for the bug report, the detail you included was very helpful.  I've found two different bugs are involved, and created separate issues for them: [issue 11](https://github.com/google/subpar/issues/11), [issue 12](https://github.com/google/subpar/issues/12).

Also, not a bug, but there is a Python standard library module called "code" which shadows your package "code".  This triggers one of the bugs, and makes the error message more confusing than it needs to be.

While they are being fixed, you can workaround the first bug by adding an `imports` attribute to your BUILD target:

```python
par_binary(
    name = "some_app",
    srcs = ["some_app.py"],
    imports = [".."],
    deps = [
        "//code/util:some_library",
        "//code/util:some_log",
    ],
)
```

Unfortunately, I can't think of a good workaround for the second bug other than renaming your "code" directory to something else.

**Comment by gnufreak** [comment] 2016-10-05 23:53
Thanks for a quick response. I think I might have added an unnecessary confusion by substituting 'myprojectname' with 'code' on the entire output, so that shadowing issue was a red-herring here.

The issue I'm having seems to be a bit different. Perhaps I misunderstood what support._setup() was intended to do.

I thought its goal was to append (or rather prepend) the archive_path and directories matching archive_path/* to sys.path and do so without tweaking imports in par_binary rules which seems like an unnecessary hassle (i.e. the deeper in the directory structure you delve the more '../../..' you'd need to manually add to make it work).

Do you agree that the stub_file produced by the vanilla py_binary rule does this correctly?

```
repo_dirs = [os.path.join(module_space, d) for d in os.listdir(module_space)]
repositories = [d for d in repo_dirs if os.path.isdir(d)]
python_path_entries += repositories
```
And then, a bit below:
```
new_env['PYTHONPATH'] = python_path
os.environ.update(new_env)
```

If I got this right, I'd be happy to send a patch for this and the related bugs. Thanks for help and please let me know.

**Comment by duggelz** [comment] 2016-10-06 00:23
Short answer: Yes and yes

Long answer: I'm a bit conflicted.  There are many different ways to structure source code, and it's hard to add implicit behavior that works for everyone.  The more things we add to sys.path, the more possibilities there are for strange name conflicts to arise.  So I lean toward explicit: explicit workspace names (e.g. the "subpar" workspace is named "subpar"), explicit "imports" attributes in BUILD rules when needed, and longer package lines like "import subpar.compiler.stored_resource" vs just "import compiler.stored_resource".

However, I also think the benefit from exactly matching the behavior of Bazel's stub file trumps this concern.  So, yes.

Note that the additional entries should actually be inserted immediately after sys.path[0] (which is the par file itself).

**Comment by duggelz** [comment] 2016-12-07 23:17
Should be fixed now.  Please verify.

**Closed by duggelz** 2016-12-07 23:17 UTC
